trainingmix_component=training - Components

training_helloWorld=Hello World
training_helloWorld.name=Name

training_helloCard=Hello Card
training_helloCard.title=Title
training_helloCard.illustration=Illustration
training_helloCard.illustration.code=A developer coding
training_helloCard.illustration.coffee=Buying coffee
training_helloCard.illustration.interface=Consulting an interface
training_helloCard.illustration.read=Looking at a bookshelf
training_helloCard.illustration.write=Writing with a typewriter
